In [1]:
import numpy as np

In [3]:
x = np.random.rand(2,3,4)
x

array([[[0.30330256, 0.41846728, 0.69623816, 0.05007753],
        [0.71297916, 0.92490919, 0.77109892, 0.3873521 ],
        [0.85832798, 0.78649651, 0.13370443, 0.95604256]],

       [[0.93322181, 0.12941934, 0.67637193, 0.69885988],
        [0.88574069, 0.26758406, 0.15032769, 0.32390954],
        [0.12777188, 0.3762153 , 0.80478355, 0.18824842]]])

In [5]:
x[:, :6, :] -= np.mean(x[:, :6, :], axis=2, keepdims=True)

In [6]:
x[:, 6:, :] = x[:, 6:, :] * 2.0 - 1.0

array([[[ 2.77555756e-17],
        [-5.55111512e-17],
        [ 5.55111512e-17]],

       [[ 5.55111512e-17],
        [ 0.00000000e+00],
        [ 0.00000000e+00]]])

In [7]:
x

array([[[-0.06371882,  0.0514459 ,  0.32921678, -0.31694385],
        [ 0.01389432,  0.22582435,  0.07201408, -0.31173274],
        [ 0.17468511,  0.10285364, -0.54993844,  0.27239969]],

       [[ 0.32375357, -0.4800489 ,  0.06690369,  0.08939164],
        [ 0.4788502 , -0.13930644, -0.25656281, -0.08298096],
        [-0.24648291,  0.00196051,  0.43052876, -0.18600636]]])

9.99999993922529e-09